server.port=8082

# Conexao MySQL (task-db)
spring.datasource.url=jdbc:mysql://localhost:3307/task_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=app_user
spring.datasource.password=app_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Mesma chave secreta do auth-service para validar o JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970